BOARD_TAG = uno
PORT = /dev/cu.wchusbserial10
DEVICE_PATH = /dev/cu.wchusbserial10
MONITOR_PORT = /dev/cu.wchusbserial10
CURRENT_DIR       = $(shell basename $(CURDIR))
OBJDIR            = dist/
LOCAL_INO_SRCS		= hyperion_ws2812/hyperion_ws2812.ino
include $(ARDMK_DIR)/Arduino.mk
